import type { DatabaseColumn, DatabaseExplorer, DatabaseForeignKey, DatabaseTable } from '$lib/rpc';
import { resolveOutgoingRelations } from '$lib/utils/relation-resolve';
import { findExplorerTable } from '$lib/utils/schema-objects';

export type GridColumnKind = 'boolean' | 'number' | 'date' | 'datetime' | 'text' | 'fk';

export type GridColumnMeta = {
	name: string;
	kind: GridColumnKind;
	notNull: boolean;
	isPrimary: boolean;
	isAuto: boolean;
	/** True when the database defines a column default, so empty drafts may be omitted on insert. */
	hasDefault: boolean;
	fk: DatabaseForeignKey | null;
	dataType: string;
};

const BOOLEAN_TYPE = /\b(boolean|bool|bit|tinyint\s*\(\s*1\s*\))\b/i;
const INTEGER_TYPE = /\b(int|integer|smallint|bigint|serial|bigserial|smallserial|tinyint|mediumint)\b/i;
const DECIMAL_TYPE = /\b(numeric|decimal|real|double|float|money)\b/i;
const DATETIME_TYPE = /\b(timestamp|timestamptz|datetime)\b/i;

function normalizedDataType(dataType: string): string {
	return dataType.toLowerCase().split('(')[0]?.trim() ?? '';
}
const AUTO_TYPE = /\b(serial|bigserial|smallserial|identity|auto_increment)\b/i;
const LABEL_HINTS = [
	'name',
	'title',
	'email',
	'username',
	'label',
	'code',
	'full_name',
	'display_name',
];

function namesEqual(a: string, b: string): boolean {
	return a === b || a.toLowerCase() === b.toLowerCase();
}

export function isBooleanDataType(dataType: string): boolean {
	return BOOLEAN_TYPE.test(dataType);
}

export function isNumericDataType(dataType: string): boolean {
	return INTEGER_TYPE.test(dataType) || DECIMAL_TYPE.test(dataType);
}

export function isIntegerDataType(dataType: string): boolean {
	return INTEGER_TYPE.test(dataType) && !DECIMAL_TYPE.test(dataType);
}

export function isUuidDataType(dataType: string): boolean {
	return /\b(uuid|uniqueidentifier)\b/i.test(dataType);
}

export function isAutoGeneratedColumn(column: DatabaseColumn): boolean {
	if (AUTO_TYPE.test(column.dataType)) return true;
	if (!column.isPrimary) return false;
	if (isIntegerDataType(column.dataType) || isUuidDataType(column.dataType)) return true;
	return column.name.toLowerCase() === 'id';
}

export function columnKindFor(
	column: DatabaseColumn,
	fk: DatabaseForeignKey | null,
	sample: unknown,
): GridColumnKind {
	if (fk) return 'fk';
	if (isBooleanDataType(column.dataType) || typeof sample === 'boolean') return 'boolean';
	if (DATETIME_TYPE.test(column.dataType)) return 'datetime';
	if (normalizedDataType(column.dataType) === 'date') return 'date';
	if (isNumericDataType(column.dataType) || typeof sample === 'number') return 'number';
	return 'text';
}

export function gridColumnsForTable(
	explorer: DatabaseExplorer | null,
	context: { schema: string; table: string } | null,
	visibleColumns: string[],
	sampleValue: (column: string) => unknown,
): GridColumnMeta[] {
	const table = context
		? findExplorerTable(explorer, context.schema, context.table)
		: null;
	return visibleColumns.map((name) => {
		const column =
			table?.columns.find((item) => namesEqual(item.name, name)) ??
			({
				name,
				dataType: 'text',
				notNull: false,
				isPrimary: false,
				hasDefault: false,
			} satisfies DatabaseColumn);
		const fk = context
			? (resolveOutgoingRelations(explorer, context, name)[0] ?? null)
			: null;
		return {
			name,
			kind: columnKindFor(column, fk, sampleValue(name)),
			notNull: column.notNull,
			isPrimary: column.isPrimary,
			isAuto: isAutoGeneratedColumn(column),
			hasDefault: column.hasDefault === true,
			fk,
			dataType: column.dataType,
		};
	});
}

export function parseBooleanDraft(raw: string): boolean | null {
	const normalized = raw.trim().toLowerCase();
	if (normalized === '') return null;
	if (['1', 'true', 'yes', 'on', 't', 'y'].includes(normalized)) return true;
	if (['0', 'false', 'no', 'off', 'f', 'n'].includes(normalized)) return false;
	return null;
}

export function coerceByColumn(raw: string, meta: GridColumnMeta | undefined, sample: unknown): unknown {
	if (raw.trim() === '') return null;
	const kind = meta?.kind;
	if (kind === 'boolean' || typeof sample === 'boolean') {
		return parseBooleanDraft(raw) ?? raw;
	}
	if (kind === 'number' || typeof sample === 'number') {
		const num = Number(raw);
		return Number.isNaN(num) ? raw : num;
	}
	return raw;
}

export function formatBooleanLabel(value: unknown): string {
	if (value === true || value === 'true' || value === 1 || value === '1') return 'True';
	if (value === false || value === 'false' || value === 0 || value === '0') return 'False';
	return '';
}

export function isEmptyCell(value: unknown): boolean {
	return value === null || value === undefined || value === '';
}

export function displayCellText(value: unknown, meta: GridColumnMeta | undefined): string {
	if (isEmptyCell(value)) return '';
	if (meta?.kind === 'boolean') return formatBooleanLabel(value) || String(value);
	return String(value);
}

export function valuesForInsert(
	draft: Record<string, string>,
	columns: GridColumnMeta[],
	sampleValue: (column: string) => unknown,
): Record<string, unknown> {
	const values: Record<string, unknown> = {};
	for (const column of columns) {
		const raw = draft[column.name] ?? '';
		if (raw.trim() === '') {
			// Omit auto, primary-key, nullable, and defaulted columns so the
			// database can fill them in. Anything else is sent as NULL so the
			// database (not a possibly-stale client guess) enforces NOT NULL.
			if (column.isAuto || column.isPrimary || !column.notNull || column.hasDefault)
				continue;
			values[column.name] = null;
			continue;
		}
		values[column.name] = coerceByColumn(raw, column, sampleValue(column.name));
	}
	return values;
}

export function missingRequiredColumns(
	draft: Record<string, string>,
	columns: GridColumnMeta[],
): string[] {
	return columns
		.filter((column) => {
			if (column.isAuto || column.isPrimary || !column.notNull) return false;
			// A database default satisfies the NOT NULL constraint on insert.
			if (column.hasDefault) return false;
			return (draft[column.name] ?? '').trim() === '';
		})
		.map((column) => column.name);
}

export function pickFkLabelColumns(table: DatabaseTable | null, idColumn: string): string[] {
	if (!table) return [];
	const names = table.columns.map((column) => column.name);
	const picked: string[] = [];
	for (const hint of LABEL_HINTS) {
		const match = names.find(
			(name) =>
				!namesEqual(name, idColumn) &&
				(name.toLowerCase() === hint ||
					name.toLowerCase().endsWith(`_${hint}`) ||
					name.toLowerCase().includes(hint)),
		);
		if (match && !picked.some((item) => namesEqual(item, match))) picked.push(match);
		if (picked.length >= 2) break;
	}
	if (picked.length === 0) {
		const fallback = names.find(
			(name) =>
				!namesEqual(name, idColumn) &&
				!isNumericDataType(
					table.columns.find((column) => namesEqual(column.name, name))?.dataType ?? '',
				),
		);
		if (fallback) picked.push(fallback);
	}
	return picked;
}

export function formatFkOptionLabel(id: unknown, labels: unknown[]): string {
	const readable = labels
		.map((item) => (item == null ? '' : String(item).trim()))
		.filter((item) => item.length > 0);
	if (readable.length === 0) return String(id);
	return `${readable.join(' · ')}`;
}
