import { describe, expect, it } from 'vitest';
import { shopExplorer } from '$lib/utils/relation-fixtures';
import {
	coerceByColumn,
	displayCellText,
	gridColumnsForTable,
	isAutoGeneratedColumn,
	missingRequiredColumns,
	parseBooleanDraft,
	pickFkLabelColumns,
	valuesForInsert,
} from '$lib/utils/grid-editors';

const explorer = shopExplorer();

describe('grid editors', () => {
	it('detects boolean drafts', () => {
		expect(parseBooleanDraft('true')).toBe(true);
		expect(parseBooleanDraft('No')).toBe(false);
		expect(parseBooleanDraft('')).toBeNull();
	});

	it('treats integer primary keys as automatic', () => {
		expect(
			isAutoGeneratedColumn({
				name: 'id',
				dataType: 'integer',
				notNull: true,
				isPrimary: true,
			}),
		).toBe(true);
		expect(
			isAutoGeneratedColumn({
				name: 'id',
				dataType: 'text',
				notNull: true,
				isPrimary: true,
			}),
		).toBe(true);
		expect(
			isAutoGeneratedColumn({
				name: 'email',
				dataType: 'text',
				notNull: true,
				isPrimary: false,
			}),
		).toBe(false);
		expect(
			isAutoGeneratedColumn({
				name: 'email',
				dataType: 'text',
				notNull: true,
				isPrimary: true,
			}),
		).toBe(false);
	});

	it('skips empty auto and optional columns on insert', () => {
		const columns = gridColumnsForTable(
			explorer,
			{ schema: 'public', table: 'orders' },
			['id', 'customer_id'],
			() => 1,
		);
		expect(columns.find((item) => item.name === 'customer_id')?.kind).toBe('fk');
		expect(
			valuesForInsert({ id: '', customer_id: '9' }, columns, () => 1),
		).toEqual({ customer_id: 9 });
	});

	it('requires not-null fields that are not automatic', () => {
		const columns = gridColumnsForTable(
			explorer,
			{ schema: 'public', table: 'users' },
			['id', 'email'],
			() => null,
		);
		expect(missingRequiredColumns({ id: '', email: '' }, columns)).toEqual(['email']);
	});

	it('picks a human label column for FK options', () => {
		const users = explorer.schemas[0]?.tables.find((table) => table.name === 'users');
		expect(pickFkLabelColumns(users ?? null, 'id')).toEqual(['email']);
	});

	it('formats boolean cells for people, not SQL', () => {
		expect(displayCellText(true, { name: 'active', kind: 'boolean', notNull: true, isPrimary: false, isAuto: false, hasDefault: false, fk: null, dataType: 'boolean' })).toBe('True');
		expect(displayCellText(null, { name: 'active', kind: 'boolean', notNull: false, isPrimary: false, isAuto: false, hasDefault: false, fk: null, dataType: 'boolean' })).toBe('');
	});

	it('shows raw foreign key ids in the grid', () => {
		expect(
			displayCellText('cmtd5vcz20003vm2p0klqm6fe', {
				name: 'uploaderId',
				kind: 'fk',
				notNull: false,
				isPrimary: false,
				isAuto: false,
				hasDefault: false,
				fk: {
					column: 'uploaderId',
					referencedSchema: 'public',
					referencedTable: 'User',
					referencedColumn: 'id',
				},
				dataType: 'text',
			}),
		).toBe('cmtd5vcz20003vm2p0klqm6fe');
	});

	it('coerces boolean and number drafts', () => {
		expect(
			coerceByColumn('false', {
				name: 'active',
				kind: 'boolean',
				notNull: true,
				isPrimary: false,
				isAuto: false,
				hasDefault: false,
				fk: null,
				dataType: 'boolean',
			}, true),
		).toBe(false);
		expect(
			coerceByColumn('12', {
				name: 'qty',
				kind: 'number',
				notNull: true,
				isPrimary: false,
				isAuto: false,
				hasDefault: false,
				fk: null,
				dataType: 'integer',
			}, 0),
		).toBe(12);
	});

	it('does not require defaulted columns on insert', () => {
		const columns = gridColumnsForTable(
			{
				database: 'shop',
				schemas: [
					{
						name: 'public',
						tables: [
							{
								schema: 'public',
								name: 'events',
								kind: 'table',
								columns: [
									{ name: 'id', dataType: 'bigint', notNull: true, isPrimary: true },
									{ name: 'email', dataType: 'text', notNull: true, isPrimary: false },
									{
										name: 'created_at',
										dataType: 'timestamptz',
										notNull: true,
										isPrimary: false,
										hasDefault: true,
									},
								],
								foreignKeys: [],
							},
						],
					},
				],
			},
			{ schema: 'public', table: 'events' },
			['id', 'email', 'created_at'],
			() => null,
		);
		expect(columns.find((item) => item.name === 'created_at')?.hasDefault).toBe(true);
		expect(missingRequiredColumns({ id: '', email: 'a@b.c', created_at: '' }, columns)).toEqual(
			[],
		);
		expect(
			valuesForInsert({ id: '', email: 'a@b.c', created_at: '' }, columns, () => null),
		).toEqual({ email: 'a@b.c' });
	});
});
